### ISSUE TITLE
In the complex example, CVE-2018-18495, no CWE is assigned

### ISSUE THREAD

**Issue by kernelsmith** [RedHatProductSecurity/cwe-toolkit#3]
The complex example in the readme is `CWE-20->CWE-805->(CWE-125|CWE-787` which can be worded as 
`Improper Input Validation leads to Buffer Access with Incorrect Index leads to either Out-of-bounds Read or Out-of-bounds Write` but the CVE doesn't officially have a CWE assigned. Additionally, NVD has assigned CWE-732 which doesn't appear in the chain at all. I was wondering, if this was CVE JSON v5.x, what `problemType` would you assign (assuming you assign a CWE for the `problemType`)?

**Comment by mprpic** [comment]
> but the CVE doesn't officially have a CWE assigned

It does in our CVE database: https://access.redhat.com/security/cve/CVE-2014-8098

NIST assigns CWEs themselves so whatever CWE shows up in NVD is not one that Red Hat would necessarily assign (as is the case here). Same goes for CVSS scores, which is why we show both on our CVE pages and sometimes explain the difference if there is one, e.g.: [CVE-2023-36665](https://access.redhat.com/security/cve/CVE-2023-36665). We don't have such a mechanism (show both, and provide comment on differences) for CWEs unfortunately.

> I was wondering, if this was CVE JSON v5.x, what `problemType` would you assign (assuming you assign a CWE for the `problemType`)?

In the v5 CVE schema, we simply show the last one in the chain but do provide the full chain in a custom `x_redhatCweChain` attribute. I don't see any CVEs since we started publishing v5 that have been assigned by Red Hat and have a more complex CWE yet though so can't really point to a live example, but it would look something like this for `CWE-20->CWE-805->(CWE-125|CWE-787)`:

```json
"problemTypes": [
    {
        "descriptions": [
            {
                "cweId": "CWE-787",
                "description": "Out-of-bounds Write",
                "lang": "en",
                "type": "CWE",
            }
        ]
    }
],
"x_redhatCweChain": "CWE-20->CWE-805->(CWE-125|CWE-787)",
```

**Comment by kernelsmith** [comment]
yeah, we get some interesting CWE comments/choices from NVD too. Sometimes they are valid. Either way, we're less vested in the ultimate choice because we're almost always talking about a 3rd party's product, not our own, so we don't have access to source and it's all based on reverse engineering which doesn't always give us enough to form a steadfast opposing position etc.

Re: the CWE in JSON5, perfect, that's exactly what I was wondering (which in the chain you "officially" apply). Using `x_redhatCweChain` is a great approach, even gives NVD an idea for how the analysis progressed. As you might infer, I'm looking at cwe toolkit to see if our analysts or analysis would benefit from that approach (tho I realize it's more about the process than it is the toolkit.
